GET http://localhost:3028/getAuthors


####


POST http://localhost:3028/createAuthor
Content-Type: application/json

{
    "name": "Luca",
    "surname": "Rossi",
    "email": "emailprova@email.it",
    "date_of_birth": "15/07/1998",
    "avatar": "M"
}

####

GET http://localhost:3028/getAuthor/65f0731b93524eb16e88d030

####

PATCH http://localhost:3028/updateAuthor/65f0731b93524eb16e88d030
Content-Type: application/json

{
    "surname": "Pasc"
}

####

DELETE http://localhost:3028/deleteAuthor/65f07d468bf3c0c6509ddb88